/*
 * @Descripttion:
 * @version:
 * @Author: joshua
 * @Date: 2020-05-18 14:51:03
 * @LastEditors: joshua
 * @LastEditTime: 2020-05-30 01:00:21
 */
package main

import (
	"github.com/joshua-chen/go-commons/mvc/application"

	"shap_wap/routes"
	_ "time"

	"github.com/iris-contrib/swagger/v12"
	"github.com/iris-contrib/swagger/v12/swaggerFiles"
	"github.com/kataras/iris/v12"

	_ "shap_wap/docs" //  docs is generated by Swag CLI, you have to import it.
)

// @title Swagger Product API
// @version 1.0
// @description Product server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url https://github.com/joshua-chen
// @contact.email joshua_chen@qq.com

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host
// @basePath /api/v1/wap
func main() {	
	application.Run(func(app *iris.Application) {
		routes.Register(app)
		swaggerConfig := &swagger.Config{
			URL: "/swagger/doc.json", //The url pointing to API definition
		}
		// use swagger middleware to
		app.Get("/swagger/{any:path}", swagger.CustomWrapHandler(swaggerConfig, swaggerFiles.Handler))
	})
}
