basePath: /api/product/v1
info:
  contact:
    email: joshua_chen@qq.com
    name: API Support
    url: https://github.com/joshua-chen
  description: Product server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Product API
  version: "1.0"
paths:
  /products:
    get:
      consumes:
      - application/x-json-stream
      description: 获取产品
swagger: "2.0"
